### ISSUE TITLE
Issue-1-user-can-search-location

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#1]
## 💰 Motivation

Ability to have search bar activity

## 📐 Plan

Create form for submitting a location request to the API

## 🖼️ Wireframes
<img width="719" alt="Screen Shot 2022-04-11 at 10 05 01 AM" src="https://user-images.githubusercontent.com/97134047/162792937-3e591068-494f-4165-8e65-b7ad081d73ab.png">

## ✅ Task List

- [x] Import Esri JavaScript API dependencies @arcgis/core and @arcgis/webpack-plugin
- [x] Create file for the map API
- [x] Create/import new variable to view the map
- [x] Center the map to specific long, lat
- [x] Create/import  new variable to search through the map
- [x] Add map search to the top right of the webpage
- [x] Create/import basemap toggle to view basemaps
- [x] Add basemap gallery to the bottom right corner
- [x] export default App
