### ISSUE TITLE
Issue-3-User-Can-View-Stored-Marker

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#12]
## 💰 Motivation

Ability to view the marker saved to the specific longitude and latitude

## 📐 Plan

Allow marker to be consistently viewed once stored to the server

## 🖼️ Wireframes
![Screen Shot 2022-04-11 at 11 55 40 AM](https://user-images.githubusercontent.com/97134047/162809925-0a2afcb8-9646-49ce-861a-aa29dcbdc4f7.png)

## ✅ Task List

- [x] allow client-side Map communicate with the server OR
- [x] create new component for the marker 
- [x] create variables to communicate with server / lift state
- [x] add element to the return within the `<GoogleMap>` react element to view on page
