### ISSUE TITLE
Issue-6-stretch-user-can-search-location

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to use a search bar to find a specific location in the world.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Easier ability to move to a specific location based on where the user recorded their soundscape.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the
<img width="1439" alt="Screen Shot 2022-04-17 at 10 06 57 PM" src="https://user-images.githubusercontent.com/97134047/163757744-0d08b638-a8c8-495b-b132-a6df5c134b48.png">
 app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component for the `SearchBox` grabbed from the @react google api
- [ ] import the `StandaloneSearchBox` from the `node_module`
- [ ] Use hook useState with deconstructed array [searchBox, setSearchBox]
- [ ] setSearchBox while passing parameter, ref
- [ ] insert return for the function passing the react element component `StandaloneSearchBox`
- [ ] within the react element content create an `<input>` to design the searchbox
- [ ] console.log the variable `onPlacesChanged` with the method `getPlaces()`
- [ ] Pass the react component element for `SearchBox` function into the `<GoogleMaps>`

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
