### ISSUE TITLE
Issue-7-user-can-view-audio-progress-bar

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to use a the audio's progress bar to see the progress of the audio clip. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Ability to see the length and progress of the audio clip.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="625" alt="Screen Shot 2022-04-19 at 1 52 56 PM" src="https://user-images.githubusercontent.com/97134047/164093788-110e267e-1dc9-41d8-b816-1bfc25549dba.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Work on the audioplayer - maybe think about making it into a component
- [x] If component, determine what to target to enable the audio to play on browser
- [x] create `useRef` for the progress bar to reference
- [x] create hook for `useEffect` to gather the duration of the audio player for the run time
- [x] create function `changePlayerCurrentTime` to show the current runtime of the audio clip
- [x] create `useState` hook with a deconstructed array for the `currentTime`, `setCurrentTime`
- [x] pass the `setProperty` function into `changePlayerCurrentTime` 
- [x] pass in a function to calculate the time of the audio clip - returning minutes : seconds
- [x] Create function for the animation to run while the audio player is playing
- [x] within the return of the `AudioPlayer` for the progress bar's `<input>` use the reference for the progress bar and `changeRange` for the `onChange`

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
