### ISSUE TITLE
Issue-2-user-can-view-location

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#2]
## 💰 Motivation

Ability to have search bar activity

## 📐 Plan

Create form for submitting a location request to the API

## 🖼️ Wireframes
![Screen Shot 2022-04-11 at 11 42 28 AM](https://user-images.githubusercontent.com/97134047/162807691-357d79aa-3b7d-4948-83b0-0768fe924cc7.png)

## ✅ Task List

- [ ] On search, user is taken to location on the API map
- [ ] Create/import Locate for users to geolocate their locations
- [ ] Add API key for users to access app without needing to log in
