### ISSUE TITLE
Issue-8-user-can-geolocate-position

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to use a search bar to find a specific location in the world.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Easier ability to move to a specific location based on where the user recorded their soundscape.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like

<img width="514" alt="Screen Shot 2022-04-21 at 3 09 38 PM" src="https://user-images.githubusercontent.com/97134047/164559889-1e4e262e-05c8-411a-91f7-f4fc3b49558c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a function for `GeoLocate` 
- [x] in the return of the function use the `getCurrentPosition` method
- [x] use an anonymous function to `panTo` the position.coords for longitude and latitude
- [x] use the `setZoom` method of the `map` object
- [x] add text to button indicating `Find me!`
- [x] Remove `mapRef` with useCallBack hook, unnecessary as the `GeoLocate` will be passed into hook
- [x] Use hook `useCallBack` with variable name `onMapLoad` with anonymous function with first parameter as `map`
- [x] inside curly brace for anonymous function create a `div` for the `GeoLocate` button
- [x] position the `GeoLocate` button to be in the top right of the page via the `ControlPosition` property
- [x] render the `GeoLocate` function with a `map` attribute and the `div` 
- [x] add the `GeoLocate` as a react element to the return of the `Map` component 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
