### ISSUE TITLE
Issue-2-user-can-upload-soundscape

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#3]
## 💰 Motivation

Ability to upload soundscapes

## 📐 Plan

Create pin on uploading recorded soundscapes to a specific location

## 🖼️ Wireframes
![Screen Shot 2022-04-11 at 11 49 57 AM](https://user-images.githubusercontent.com/97134047/162808899-68bce49f-8b87-4311-bee0-1b3c27175b5c.png)

## ✅ Task List
- [x] Hard code example content pop-up
- [x] with hard code, target view.graphics.add to insert the symbol used for the esri icon
- [x] point the geometry with the longitude and latitude
- [x] target the popupTemplate
- [x] hardcode in a new featureLayer
- [x] add dummy objects into layer
- [x] see if editor will allow for posting new objects via points to layer

for client side:
- [x] Add click event to target the lat, long of location
- [ ] on click event, pop-up propagates to insert file
- [x] Create file for adding FormData 
- [x] make sure postgresql is running
- [x] createdb soundscapes
- [x] install the multer package for handling form-data
- [x] create handleSubmit event
- [x] create a new FormData object 
- [x] use fetch request to target the soundscape uploads
- [x] then, parse JSON response body 
- [x] then, log the parsed response body
- [x] catch error in promise chain

for server side:

- [x] create a url for the mp3 
- [x] insert into table
- [x] respond with inserted row data
- [x] catch any errors
