### ISSUE TITLE
Bug: Close modal and add marker

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#32]
#### Desired Behavior

> ##### The app should ...

Close the modal and add the marker submitted to server

#### Actual Behavior

> ##### The app does this instead ...

Would not submit form to server, needed to add `event.preventDefault` to `handleSubmit`. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

remove `event.preventDefault` from the  `handleSubmit`. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] lift state from child component onSubmit to parent to close the modal which is on the parent
- [x] close modal `onSubmit`
- [x] add marker `onSubmit`
- [x] - **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
