### ISSUE TITLE
Issue-4-user-can-listen-to-soundscape

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#5]
## 💰 Motivation

Ability to listen to uploaded soundscapes

## 📐 Plan

Allow audio functionality to soundscape that was uploaded 

## 🖼️ Wireframes
![Screen Shot 2022-04-11 at 11 55 40 AM](https://user-images.githubusercontent.com/97134047/162809925-0a2afcb8-9646-49ce-861a-aa29dcbdc4f7.png)

## ✅ Task List

- [x] construct audio player using `<audio>`
- [x] target the `fileUrl` and ensure pathing is correct
- [x] create a useState hook
- [x] destructor an array within the useState hook with values to play the audio and set the audio
- [x] togglePlayPause to setIsPlaying to either be true or false
- [x] subtle styling to the play / pause buttons
