### ISSUE TITLE
Bug: inability to render data

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/final-project#8]
#### Desired Behavior

> ##### The app should...

The app should allow users to create own point to create their soundscape

#### Actual Behavior

> ##### The app does this instead ...

does not allow users to do anything with the point they create 
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

The app should allow users to create own point to 
## ✅ Task List

- [x] continue looking through documentation
- [x] create a dummy FeatureLayer to see if creation of soundscapes and listening to audio is possible on this API
- [x] if dummy data is successful, add editor layer to enable editing of points on layer
- [x] if editor is successful, allow the editor to create new points onto the layer
